$kind: http-request
name: Create Webhook Config
method: POST
url: "{{baseUrl}}/v1/merchants/webhooks/create"
examples: .resources/create-webhook-config.resources/examples
order: 1000
headers:
  - key: Content-Type
    value: application/json
  - key: X-Idempotency-Key
    value: "{{$guid}}"
    description: Optional idempotency key to prevent duplicate webhook config creation
body:
  type: json
  content: |-
    {
      "targetUrl": "http:///localhost:8080/v1/merchant/webhooks",
      "eventTypes": "ALL"
    }
scripts:
  - type: afterResponse
    code: |-
      pm.test("Status is 200 OK", function () {
          pm.response.to.have.status(200);
      });
      pm.test("Response has webhook config id", function () {
          var json = pm.response.json();
          pm.expect(json).to.have.property("id");
          pm.expect(json).to.have.property("targetUrl");
          pm.expect(json).to.have.property("webhookSecret");
          pm.collectionVariables.set("webhookConfigId", json.id);
      });
    language: text/javascript
